risk_data = [
    {
        'name': 'Fire at Warehouse',
        'description': 'A fire broke out at the warehouse due to an electrical fault.',
        'user': 'admin',
        'provider': 'ABC Insurance Company',
        'country': 'United States',
        'country_info': 'US United States - Washington D.C.',
        'impact': 'High',
        'probability': 'Medium',
        'level': 'Critical',
    },
    {
        'name': 'Supply Chain Disruption',
        'description': 'A major supplier faced a production halt, impacting our supply chain.',
        'user': 'admin',
        'provider': 'XYZ Logistics',
        'country': 'China',
        'country_info': 'CN China - Beijing',
        'impact': 'Medium',
        'probability': 'High',
        'level': 'High',
    },
    {
        'name': 'Data Breach',
        'description': 'A security breach led to unauthorized access to customer data.',
        'user': 'admin',
        'provider': 'Security Solutions Inc.',
        'country': 'Germany',
        'country_info': 'DE Germany - Berlin',
        'impact': 'High',
        'probability': 'Low',
        'level': 'High',
    },
    {
        'name': 'Natural Disaster - Earthquake',
        'description': 'A powerful earthquake struck the region, causing widespread damage.',
        'user': 'admin',
        'provider': 'Disaster Relief Organization',
        'country': 'Japan',
        'country_info': 'JP Japan - Tokyo',
        'impact': 'High',
        'probability': 'Low',
        'level': 'High',
    },
    {
        'name': 'Financial Market Volatility',
        'description': 'Sudden fluctuations in financial markets led to investment losses.',
        'user': 'admin',
        'provider': 'Investment Advisors Ltd.',
        'country': 'United Kingdom',
        'country_info': 'GB United Kingdom - London',
        'impact': 'High',
        'probability': 'Medium',
        'level': 'High',
    },
    {
        'name': 'Cybersecurity Breach',
        'description': 'A cyberattack resulted in a breach of sensitive information.',
        'user': 'admin',
        'provider': 'Cybersecurity Experts LLC',
        'country': 'Canada',
        'country_info': 'CA Canada - Ottawa',
        'impact': 'High',
        'probability': 'Medium',
        'level': 'High',
    },
    {
        'name': 'Political Instability',
        'description': 'Ongoing political unrest affected operations in the region.',
        'user': 'admin',
        'provider': 'Global Political Risk Advisors',
        'country': 'Brazil',
        'country_info': 'BR Brazil - Brasília',
        'impact': 'Medium',
        'probability': 'High',
        'level': 'High',
    },
    {
        'name': 'Environmental Pollution Incident',
        'description': 'A chemical spill caused environmental harm and legal liabilities.',
        'user': 'admin',
        'provider': 'Environmental Consultants Inc.',
        'country': 'Australia',
        'country_info': 'AU Australia - Canberra',
        'impact': 'Medium',
        'probability': 'Medium',
        'level': 'High',
    },
    {
        'name': 'Regulatory Compliance Issue',
        'description': 'Non-compliance with new regulations led to legal penalties.',
        'user': 'admin',
        'provider': 'Regulatory Compliance Advisors',
        'country': 'France',
        'country_info': 'FR France - Paris',
        'impact': 'Medium',
        'probability': 'Low',
        'level': 'Medium',
    },
    {
        'name': 'Market Competition Intensification',
        'description': 'Increased competition in the market impacted market share.',
        'user': 'admin',
        'provider': 'Market Research Firm Ltd.',
        'country': 'India',
        'country_info': 'IN India - New Delhi',
        'impact': 'Medium',
        'probability': 'Medium',
        'level': 'Medium',
    },
    {
        'name': 'Legal Dispute with a Supplier',
        'description': 'A legal dispute with a supplier led to disruptions in the supply chain.',
        'user': 'admin',
        'provider': 'Legal Advisors Associates',
        'country': 'South Africa',
        'country_info': 'ZA South Africa - Pretoria',
        'impact': 'Medium',
        'probability': 'Medium',
        'level': 'Medium',
    },
    {
        'name': 'Technological System Failure',
        'description': 'A critical technological system failure caused operational disruptions.',
        'user': 'admin',
        'provider': 'Technology Solutions Ltd.',
        'country': 'Russia',
        'country_info': 'RU Russia - Moscow',
        'impact': 'High',
        'probability': 'Low',
        'level': 'High',
    },
    {
        'name': 'Social Media Crisis',
        'description': 'A negative social media event resulted in reputation damage.',
        'user': 'admin',
        'provider': 'Social Media Management Agency',
        'country': 'Mexico',
        'country_info': 'MX Mexico - Mexico City',
        'impact': 'Medium',
        'probability': 'Medium',
        'level': 'Medium',
    },
    {
        'name': 'Regulatory Changes',
        'description': 'Sudden regulatory changes impacted business operations.',
        'user': 'admin',
        'provider': 'Regulatory Consultants Group',
        'country': 'Spain',
        'country_info': 'ES Spain - Madrid',
        'impact': 'Medium',
        'probability': 'Medium',
        'level': 'Medium',
    },
    {
        'name': 'Health and Safety Incident',
        'description': 'A workplace incident led to injuries and regulatory investigations.',
        'user': 'admin',
        'provider': 'Health and Safety Consultants Inc.',
        'country': 'Italy',
        'country_info': 'IT Italy - Rome',
        'impact': 'Medium',
        'probability': 'Low',
        'level': 'Medium',
    },
    {
        'name': 'Economic Recession',
        'description': 'A sudden economic downturn led to reduced consumer spending.',
        'user': 'admin',
        'provider': 'Economic Analysis Group',
        'country': 'Argentina',
        'country_info': 'AR Argentina - Buenos Aires',
        'impact': 'High',
        'probability': 'Medium',
        'level': 'High',
    },
    {
        'name': 'Natural Disaster - Hurricane',
        'description': 'A powerful hurricane caused widespread damage to infrastructure.',
        'user': 'admin',
        'provider': 'Disaster Response Team',
        'country': 'Nigeria',
        'country_info': 'NG Nigeria - Abuja',
        'impact': 'High',
        'probability': 'Low',
        'level': 'High',
    },
    {
        'name': 'Trade Dispute Impact',
        'description': 'A trade dispute led to tariffs affecting international trade.',
        'user': 'admin',
        'provider': 'International Trade Advisory',
        'country': 'Turkey',
        'country_info': 'TR Turkey - Ankara',
        'impact': 'Medium',
        'probability': 'Medium',
        'level': 'Medium',
    },
    {
        'name': 'Supply Chain Complexity',
        'description': 'An intricate supply chain structure led to operational challenges.',
        'user': 'admin',
        'provider': 'Supply Chain Solutions Ltd.',
        'country': 'Saudi Arabia',
        'country_info': 'SA Saudi Arabia - Riyadh',
        'impact': 'Medium',
        'probability': 'Medium',
        'level': 'Medium',
    }
]